data <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?")
sub_data <- subset(data, data$Date == '1/2/2007' | data$Date == '2/2/2007')

png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(as.POSIXct(datetime), as.numeric(sub_data$Global_active_power),type = 'l', ylab = "Global Active Power (kilowatts)",xlab = "")
plot(as.POSIXct(datetime), as.numeric(sub_data$Voltage),type = 'l', ylab = "Voltage (volt)",xlab = "datetime")
plot(as.POSIXct(datetime), sub_data$Sub_metering_1, type = 'l', ylab = "Energy sub metering", xlab = "")
lines(as.POSIXct(datetime),sub_data$Sub_metering_2, col = "red")
lines(as.POSIXct(datetime), sub_data$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black","red","blue"))
plot(as.POSIXct(datetime), as.numeric(sub_data$Global_reactive_power),type = 'l', ylab = "Global_reactive_power",xlab = "datetime")
dev.off()
